---
- name: Run unit tests
  hosts: localhost
  gather_facts: false
  vars:
    go_ci_ignore: false
  tasks:
    - name: Run unit tests
      ansible.builtin.include_role:
        name: ansible-role-nginx
        tasks_from: unit-tests/main.ansible.yml
