---
- name: Discover all vhosts
  ansible.builtin.find:
    paths:
      - "{{ nginx_path }}/sites-available/"
      - "{{ nginx_path }}/sites-enabled/"
    recurse: true
    file_type: any
  register: nginx_vhosts_unspecified

- name: Delete unspecified vhosts
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ nginx_vhosts_unspecified.files }}"
  loop_control:
    label: "{{ item.path }}"
  when: not nginx_vhosts | selectattr('name', 'equalto', item.path | basename)
  notify: Reload nginx
