---
name: CI
'on':
  pull_request:
    paths-ignore:
      - '*.md'
      - '.gitignore'
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '.gitignore'
  schedule:
    - cron: "0 9 * * 1"

defaults:
  run:
    working-directory: 'tinyblargon.nginx'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v5
        with:
          path: 'tinyblargon.nginx'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible ansible-lint
      - name: Lint code.
        run: ansible-lint

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v5

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible
      - name: Run unit test playbook.
        run: make unit_test

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu2404
          - ubuntu2204
          - debian13
          - debian12
          - debian11

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v5
        with:
          path: 'tinyblargon.nginx'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
